"""Generated by tools/generate_automation_registry.py from automation-registry.manifest.json."""

# Do not edit by hand.

TRIGGER_TYPE_IDS = ('note.created', 'note.updated', 'note.deleted', 'note.approval_submitted', 'note.approval_approved', 'note.approval_rejected', 'note.approval_needs_changes', 'document.completed', 'thinking_session.completed', 'webhook.received', 'competitive_intelligence.urgent_finding')
ACTION_TYPE_IDS = ('send_notification', 'create_note', 'update_note', 'append_note_content', 'add_note_tags', 'remove_note_tags', 'set_note_type', 'link_notes', 'submit_for_approval', 'approve_note', 'reject_note', 'request_approval_changes', 'call_webhook', 'send_email')
CONDITION_OPERATOR_IDS = ('equals', 'not_equals', 'contains', 'not_contains', 'matches_regex', 'greater_than', 'less_than', 'exists')
NOTE_TYPE_IDS = ('note', 'web-clip', 'document', 'voice', 'ai-generated')
APPROVAL_PRIORITY_IDS = ('low', 'normal', 'high', 'critical')
HTTP_METHOD_IDS = ('POST', 'PUT', 'PATCH')
ACTION_EXECUTION = {'send_notification': 'backend', 'create_note': 'backend', 'update_note': 'backend', 'append_note_content': 'backend', 'add_note_tags': 'backend', 'remove_note_tags': 'backend', 'set_note_type': 'backend', 'link_notes': 'backend', 'submit_for_approval': 'backend', 'approve_note': 'backend', 'reject_note': 'backend', 'request_approval_changes': 'backend', 'call_webhook': 'http', 'send_email': 'http'}
