// Generated by tools/generate_automation_registry.py from automation-registry.manifest.json.
// Do not edit by hand.

export const TRIGGER_TYPE_IDS = ["note.created", "note.updated", "note.deleted", "note.approval_submitted", "note.approval_approved", "note.approval_rejected", "note.approval_needs_changes", "document.completed", "thinking_session.completed", "webhook.received", "competitive_intelligence.urgent_finding"] as const;
export const ACTION_TYPE_IDS = ["send_notification", "create_note", "update_note", "append_note_content", "add_note_tags", "remove_note_tags", "set_note_type", "link_notes", "submit_for_approval", "approve_note", "reject_note", "request_approval_changes", "call_webhook", "send_email"] as const;
export const CONDITION_OPERATOR_IDS = ["equals", "not_equals", "contains", "not_contains", "matches_regex", "greater_than", "less_than", "exists"] as const;
export const NOTE_TYPE_IDS = ["note", "web-clip", "document", "voice", "ai-generated"] as const;
export const APPROVAL_PRIORITY_IDS = ["low", "normal", "high", "critical"] as const;
export const HTTP_METHOD_IDS = ["POST", "PUT", "PATCH"] as const;
export const ACTION_EXECUTION = {"send_notification": "backend", "create_note": "backend", "update_note": "backend", "append_note_content": "backend", "add_note_tags": "backend", "remove_note_tags": "backend", "set_note_type": "backend", "link_notes": "backend", "submit_for_approval": "backend", "approve_note": "backend", "reject_note": "backend", "request_approval_changes": "backend", "call_webhook": "http", "send_email": "http"} as const;
