"""Security utilities for authentication and authorization."""
from __future__ import annotations

import base64
import hashlib
import logging
import secrets
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional, Dict, Any

import bcrypt
from jose import JWTError, jwt
from fastapi import HTTPException, status

from app.config import settings

LEGACY_BCRYPT_PREFIXES = ("$2a$", "$2b$", "$2y$")
SHA256_BCRYPT_PREFIX = "bcrypt_sha256$"
logger = logging.getLogger(__name__)


def _password_bytes(password: str) -> bytes:
    return (password or "").encode("utf-8")


def validate_password_strength(password: str) -> None:
    """Enforce a baseline password policy server-side."""
    if not password or len(password) < 10:
        raise ValueError("Password must be at least 10 characters long")
    if len(password) > 128:
        raise ValueError("Password must be at most 128 characters long")
    if not any(char.islower() for char in password):
        raise ValueError("Password must include a lowercase letter")
    if not any(char.isupper() for char in password):
        raise ValueError("Password must include an uppercase letter")
    if not any(char.isdigit() for char in password):
        raise ValueError("Password must include a number")


def _jwt_secret() -> str:
    secret = (settings.JWT_SECRET or "").strip()
    if not secret:
        raise RuntimeError("JWT secret is not configured")
    return secret


def _bcrypt_sha256_input(password: str) -> bytes:
    """Pre-hash arbitrary-length passwords into bcrypt-safe input bytes."""
    digest = hashlib.sha256(_password_bytes(password)).digest()
    return base64.b64encode(digest)


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plain password against a stored hash.

    Supports:
    - new `bcrypt_sha256$...` hashes generated by this application
    - legacy raw bcrypt hashes (`$2a$`, `$2b$`, `$2y$`)
    """
    if not plain_password or not hashed_password:
        return False

    try:
        if hashed_password.startswith(SHA256_BCRYPT_PREFIX):
            stored_hash = hashed_password[len(SHA256_BCRYPT_PREFIX):].encode("utf-8")
            return bcrypt.checkpw(_bcrypt_sha256_input(plain_password), stored_hash)

        if hashed_password.startswith(LEGACY_BCRYPT_PREFIXES):
            return bcrypt.checkpw(_password_bytes(plain_password), hashed_password.encode("utf-8"))
    except (ValueError, TypeError):
        return False

    return False


def get_password_hash(password: str) -> str:
    """Hash a password safely without bcrypt's 72-byte input limit."""
    validate_password_strength(password)
    hashed = bcrypt.hashpw(_bcrypt_sha256_input(password), bcrypt.gensalt()).decode("utf-8")
    return f"{SHA256_BCRYPT_PREFIX}{hashed}"


def create_access_token(
    data: Dict[str, Any],
    expires_delta: Optional[timedelta] = None
) -> str:
    """Create a JWT access token.
    
    Args:
        data: Payload data (must include 'sub' for user_id)
        expires_delta: Token expiration time
        
    Returns:
        JWT token string
    """
    to_encode = data.copy()
    subject = str(to_encode.get("sub") or "").strip()
    if not subject:
        raise ValueError("JWT subject is required")
    try:
        uuid.UUID(subject)
    except ValueError as exc:
        raise ValueError("JWT subject must be a valid UUID") from exc

    now = datetime.now(timezone.utc)
    if expires_delta:
        expire = now + expires_delta
    else:
        expire = now + timedelta(hours=settings.JWT_EXPIRATION_HOURS)

    to_encode.update({
        "exp": expire,
        "iat": now,
        "nbf": now,
        "iss": settings.JWT_ISSUER,
        "aud": settings.JWT_AUDIENCE,
        "jti": secrets.token_urlsafe(16),
        "type": "access"
    })
    
    encoded_jwt = jwt.encode(
        to_encode,
        _jwt_secret(),
        algorithm=settings.JWT_ALGORITHM
    )
    
    return encoded_jwt


def decode_token(token: str) -> Optional[Dict[str, Any]]:
    """Decode and validate a JWT token.
    
    Args:
        token: JWT token string
        
    Returns:
        Decoded payload or None if invalid
    """
    try:
        payload = jwt.decode(
            token,
            _jwt_secret(),
            algorithms=[settings.JWT_ALGORITHM],
            issuer=settings.JWT_ISSUER,
            audience=settings.JWT_AUDIENCE,
            options={
                "require_sub": True,
                "require_exp": True,
                "require_iat": True,
                "require_nbf": True,
                "require_iss": True,
                "require_aud": True,
                "require_jti": True,
            }
        )
        return payload
    except JWTError:
        # Backward-compatibility path for tokens minted before issuer/audience/jti/nbf
        # claims were added. This avoids forcing an immediate logout for active
        # development sessions while all newly issued tokens remain on the stricter
        # format above.
        try:
            payload = jwt.decode(
                token,
                _jwt_secret(),
                algorithms=[settings.JWT_ALGORITHM],
                options={
                    "require_sub": True,
                    "require_exp": True,
                    "require_iat": True,
                    "verify_aud": False,
                    "verify_iss": False,
                },
            )
            return payload
        except JWTError:
            return None


def get_token_payload(token: str) -> Dict[str, Any]:
    """Get token payload or raise HTTPException.
    
    Args:
        token: JWT token string
        
    Returns:
        Decoded payload
        
    Raises:
        HTTPException: If token is invalid
    """
    payload = decode_token(token)
    
    if payload is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    # Check expiration
    exp = payload.get("exp")
    if exp and datetime.now(timezone.utc).timestamp() > exp:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    # Check token type
    if payload.get("type") != "access":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token type",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    return payload
