"""add embedding column to notes

Revision ID: 88698ecedc4b
Revises: 001
Create Date: 2026-03-05 13:20:49.200043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88698ecedc4b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'metadata')
    op.add_column('chunks', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('chunks', 'metadata')
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.add_column('notes', sa.Column('embedding', sa.String(length=10000), nullable=True))
    op.add_column('notes', sa.Column('word_count', sa.Integer(), nullable=True))
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='workspacerole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_members', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='workspacerole'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('notes', 'word_count')
    op.drop_column('notes', 'embedding')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.add_column('chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('chunks', 'chunk_metadata')
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
