"""add audit_metadata to audit_logs

Revision ID: 206aa02452b6
Revises: b8c9d0e1f2a3
Create Date: 2026-04-14 16:34:45.427881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '206aa02452b6'
down_revision = 'b8c9d0e1f2a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_note_interactions_compound', table_name='note_interactions')
    op.drop_index('idx_note_interactions_note', table_name='note_interactions')
    op.drop_index('idx_note_interactions_type', table_name='note_interactions')
    op.drop_index('idx_note_interactions_user', table_name='note_interactions')
    op.drop_index('idx_note_interactions_workspace', table_name='note_interactions')
    op.drop_table('note_interactions')
    op.drop_index('ix_dead_letters_document_id', table_name='dead_letters')
    op.drop_index('ix_dead_letters_failed_at', table_name='dead_letters')
    op.drop_index('ix_dead_letters_status', table_name='dead_letters')
    op.drop_index('ix_dead_letters_task_id', table_name='dead_letters')
    op.drop_index('ix_dead_letters_task_name', table_name='dead_letters')
    op.drop_index('ix_dead_letters_workspace_id', table_name='dead_letters')
    op.drop_table('dead_letters')
    op.add_column('audit_logs', sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chunks', sa.Column('chunk_status', sa.Enum('PENDING', 'EMBEDDED', 'FAILED', name='chunkstatus'), nullable=False))
    op.add_column('chunks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_chunk_status', 'chunks', ['chunk_status'], unique=False)
    op.create_index(op.f('ix_chunks_chunk_status'), 'chunks', ['chunk_status'], unique=False)
    op.drop_constraint('embeddings_chunk_id_fkey', 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.alter_column('graph_cluster_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_cluster_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_graph_cluster_memberships_cluster_id'), 'graph_cluster_memberships', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_graph_cluster_memberships_created_at'), 'graph_cluster_memberships', ['created_at'], unique=False)
    op.create_index(op.f('ix_graph_cluster_memberships_node_id'), 'graph_cluster_memberships', ['node_id'], unique=False)
    op.create_index(op.f('ix_graph_cluster_memberships_updated_at'), 'graph_cluster_memberships', ['updated_at'], unique=False)
    op.create_index(op.f('ix_graph_cluster_memberships_workspace_id'), 'graph_cluster_memberships', ['workspace_id'], unique=False)
    op.alter_column('graph_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_clusters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_graph_clusters_created_at'), 'graph_clusters', ['created_at'], unique=False)
    op.create_index(op.f('ix_graph_clusters_updated_at'), 'graph_clusters', ['updated_at'], unique=False)
    op.create_index(op.f('ix_graph_clusters_workspace_id'), 'graph_clusters', ['workspace_id'], unique=False)
    op.alter_column('graph_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_edges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_graph_edges_created_at'), 'graph_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_graph_edges_edge_type'), 'graph_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_updated_at'), 'graph_edges', ['updated_at'], unique=False)
    op.create_index(op.f('ix_graph_edges_workspace_id'), 'graph_edges', ['workspace_id'], unique=False)
    op.alter_column('graph_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_graph_nodes_created_at'), 'graph_nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_graph_nodes_node_type'), 'graph_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_graph_nodes_normalized_label'), 'graph_nodes', ['normalized_label'], unique=False)
    op.create_index(op.f('ix_graph_nodes_updated_at'), 'graph_nodes', ['updated_at'], unique=False)
    op.create_index(op.f('ix_graph_nodes_workspace_id'), 'graph_nodes', ['workspace_id'], unique=False)
    op.alter_column('note_connection_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('note_connection_suggestions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_note_connection_suggestions_created_at'), 'note_connection_suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_note_connection_suggestions_source_note_id'), 'note_connection_suggestions', ['source_note_id'], unique=False)
    op.create_index(op.f('ix_note_connection_suggestions_status'), 'note_connection_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_note_connection_suggestions_suggested_note_id'), 'note_connection_suggestions', ['suggested_note_id'], unique=False)
    op.create_index(op.f('ix_note_connection_suggestions_updated_at'), 'note_connection_suggestions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_note_connection_suggestions_workspace_id'), 'note_connection_suggestions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_note_versions_created_at'), 'note_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_note_versions_note_id'), 'note_versions', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_versions_user_id'), 'note_versions', ['user_id'], unique=False)
    op.create_index(op.f('ix_note_versions_workspace_id'), 'note_versions', ['workspace_id'], unique=False)
    op.alter_column('notes', 'embedding',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON-serialized embedding vector for semantic search (1536D)',
               existing_nullable=True)
    op.drop_index('idx_notes_content_tsv', table_name='notes', postgresql_using='gin')
    op.drop_index('idx_notes_embedding_vector_ivf', table_name='notes', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_notes_user_updated', table_name='notes')
    op.drop_index('idx_notes_workspace_embedding', table_name='notes', postgresql_where='(embedding_vector IS NOT NULL)')
    op.drop_index('idx_notes_workspace_tsvector', table_name='notes', postgresql_where='(content_tsv IS NOT NULL)')
    op.drop_index('idx_notes_workspace_type', table_name='notes')
    op.drop_column('notes', 'content_tsv')
    op.drop_column('notes', 'embedding_json')
    op.drop_column('notes', 'embedding_vector')
    op.alter_column('search_queries', 'query_embedding',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON-serialized query embedding vector (1536D)',
               existing_nullable=True)
    op.alter_column('search_queries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_search_queries_embedding_vector_ivf', table_name='search_queries', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_search_queries_created_at'), 'search_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_search_queries_workspace_id'), 'search_queries', ['workspace_id'], unique=False)
    op.drop_constraint('search_queries_workspace_id_fkey', 'search_queries', type_='foreignkey')
    op.drop_constraint('search_queries_user_id_fkey', 'search_queries', type_='foreignkey')
    op.create_foreign_key(None, 'search_queries', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'search_queries', 'users', ['user_id'], ['id'])
    op.drop_column('search_queries', 'query_embedding_vector')
    op.alter_column('workspace_permission_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_permission_overrides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_workspace_permission_overrides_created_at'), 'workspace_permission_overrides', ['created_at'], unique=False)
    op.create_index(op.f('ix_workspace_permission_overrides_section'), 'workspace_permission_overrides', ['section'], unique=False)
    op.create_index(op.f('ix_workspace_permission_overrides_updated_at'), 'workspace_permission_overrides', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workspace_permission_overrides_user_id'), 'workspace_permission_overrides', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_permission_overrides_workspace_id'), 'workspace_permission_overrides', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_permission_overrides_workspace_id'), table_name='workspace_permission_overrides')
    op.drop_index(op.f('ix_workspace_permission_overrides_user_id'), table_name='workspace_permission_overrides')
    op.drop_index(op.f('ix_workspace_permission_overrides_updated_at'), table_name='workspace_permission_overrides')
    op.drop_index(op.f('ix_workspace_permission_overrides_section'), table_name='workspace_permission_overrides')
    op.drop_index(op.f('ix_workspace_permission_overrides_created_at'), table_name='workspace_permission_overrides')
    op.alter_column('workspace_permission_overrides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_permission_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('search_queries', sa.Column('query_embedding_vector', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'search_queries', type_='foreignkey')
    op.drop_constraint(None, 'search_queries', type_='foreignkey')
    op.create_foreign_key('search_queries_user_id_fkey', 'search_queries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('search_queries_workspace_id_fkey', 'search_queries', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_search_queries_workspace_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_created_at'), table_name='search_queries')
    op.create_index('idx_search_queries_embedding_vector_ivf', 'search_queries', ['query_embedding_vector'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('search_queries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_queries', 'query_embedding',
               existing_type=sa.TEXT(),
               comment='JSON-serialized query embedding vector (1536D)',
               existing_nullable=True)
    op.add_column('notes', sa.Column('embedding_vector', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('embedding_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('content_tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('idx_notes_workspace_type', 'notes', ['workspace_id', 'note_type', 'created_at'], unique=False)
    op.create_index('idx_notes_workspace_tsvector', 'notes', ['workspace_id'], unique=False, postgresql_where='(content_tsv IS NOT NULL)')
    op.create_index('idx_notes_workspace_embedding', 'notes', ['workspace_id'], unique=False, postgresql_where='(embedding_vector IS NOT NULL)')
    op.create_index('idx_notes_user_updated', 'notes', ['user_id', 'updated_at'], unique=False)
    op.create_index('idx_notes_embedding_vector_ivf', 'notes', ['embedding_vector'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_notes_content_tsv', 'notes', ['content_tsv'], unique=False, postgresql_using='gin')
    op.alter_column('notes', 'embedding',
               existing_type=sa.TEXT(),
               comment='JSON-serialized embedding vector for semantic search (1536D)',
               existing_nullable=True)
    op.drop_index(op.f('ix_note_versions_workspace_id'), table_name='note_versions')
    op.drop_index(op.f('ix_note_versions_user_id'), table_name='note_versions')
    op.drop_index(op.f('ix_note_versions_note_id'), table_name='note_versions')
    op.drop_index(op.f('ix_note_versions_created_at'), table_name='note_versions')
    op.drop_index(op.f('ix_note_connection_suggestions_workspace_id'), table_name='note_connection_suggestions')
    op.drop_index(op.f('ix_note_connection_suggestions_updated_at'), table_name='note_connection_suggestions')
    op.drop_index(op.f('ix_note_connection_suggestions_suggested_note_id'), table_name='note_connection_suggestions')
    op.drop_index(op.f('ix_note_connection_suggestions_status'), table_name='note_connection_suggestions')
    op.drop_index(op.f('ix_note_connection_suggestions_source_note_id'), table_name='note_connection_suggestions')
    op.drop_index(op.f('ix_note_connection_suggestions_created_at'), table_name='note_connection_suggestions')
    op.alter_column('note_connection_suggestions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('note_connection_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_graph_nodes_workspace_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_updated_at'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_normalized_label'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_node_type'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_created_at'), table_name='graph_nodes')
    op.alter_column('graph_nodes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_graph_edges_workspace_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_updated_at'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_edge_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_created_at'), table_name='graph_edges')
    op.alter_column('graph_edges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_graph_clusters_workspace_id'), table_name='graph_clusters')
    op.drop_index(op.f('ix_graph_clusters_updated_at'), table_name='graph_clusters')
    op.drop_index(op.f('ix_graph_clusters_created_at'), table_name='graph_clusters')
    op.alter_column('graph_clusters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_graph_cluster_memberships_workspace_id'), table_name='graph_cluster_memberships')
    op.drop_index(op.f('ix_graph_cluster_memberships_updated_at'), table_name='graph_cluster_memberships')
    op.drop_index(op.f('ix_graph_cluster_memberships_node_id'), table_name='graph_cluster_memberships')
    op.drop_index(op.f('ix_graph_cluster_memberships_created_at'), table_name='graph_cluster_memberships')
    op.drop_index(op.f('ix_graph_cluster_memberships_cluster_id'), table_name='graph_cluster_memberships')
    op.alter_column('graph_cluster_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_cluster_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key('embeddings_chunk_id_fkey', 'embeddings', 'chunks', ['chunk_id'], ['id'])
    op.drop_index(op.f('ix_chunks_chunk_status'), table_name='chunks')
    op.drop_index('idx_chunk_status', table_name='chunks')
    op.drop_column('chunks', 'updated_at')
    op.drop_column('chunks', 'chunk_status')
    op.drop_column('audit_logs', 'audit_metadata')
    op.create_table('dead_letters',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'REVIEWED', 'IN_RETRY', 'RESOLVED', 'ARCHIVED', 'POISONED', name='dlqstatus'), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dead_letters_pkey')
    )
    op.create_index('ix_dead_letters_workspace_id', 'dead_letters', ['workspace_id'], unique=False)
    op.create_index('ix_dead_letters_task_name', 'dead_letters', ['task_name'], unique=False)
    op.create_index('ix_dead_letters_task_id', 'dead_letters', ['task_id'], unique=False)
    op.create_index('ix_dead_letters_status', 'dead_letters', ['status'], unique=False)
    op.create_index('ix_dead_letters_failed_at', 'dead_letters', ['failed_at'], unique=False)
    op.create_index('ix_dead_letters_document_id', 'dead_letters', ['document_id'], unique=False)
    op.create_table('note_interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='note_interactions_note_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='note_interactions_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='note_interactions_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='note_interactions_pkey')
    )
    op.create_index('idx_note_interactions_workspace', 'note_interactions', ['workspace_id', 'created_at'], unique=False)
    op.create_index('idx_note_interactions_user', 'note_interactions', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_note_interactions_type', 'note_interactions', ['interaction_type'], unique=False)
    op.create_index('idx_note_interactions_note', 'note_interactions', ['note_id', 'created_at'], unique=False)
    op.create_index('idx_note_interactions_compound', 'note_interactions', ['workspace_id', 'interaction_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
