"""add embedding column to notes

Revision ID: 88698ecedc4b
Revises: 001
Create Date: 2026-03-05 13:20:49.200043
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88698ecedc4b'
down_revision = '001'
branch_labels = None
depends_on = None

workspacerole_enum = sa.Enum(
    'OWNER', 'ADMIN', 'MEMBER', 'VIEWER',
    name='workspacerole'
)


def upgrade() -> None:
    bind = op.get_bind()

    # Create enum type first for fresh databases
    workspacerole_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column('audit_logs', 'metadata')
    op.add_column(
        'chunks',
        sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.drop_column('chunks', 'metadata')
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.add_column('notes', sa.Column('embedding', sa.String(length=10000), nullable=True))
    op.add_column('notes', sa.Column('word_count', sa.Integer(), nullable=True))

    op.alter_column(
        'workspace_members',
        'role',
        existing_type=sa.VARCHAR(length=50),
        type_=workspacerole_enum,
        existing_nullable=True,
        nullable=False,
        postgresql_using='role::workspacerole'
    )
    # ### end ###


def downgrade() -> None:
    bind = op.get_bind()

    op.alter_column(
        'workspace_members',
        'role',
        existing_type=workspacerole_enum,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        nullable=True,
        postgresql_using='role::text'
    )
    op.drop_column('notes', 'word_count')
    op.drop_column('notes', 'embedding')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.add_column(
        'chunks',
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_column('chunks', 'chunk_metadata')
    op.add_column(
        'audit_logs',
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )

    # Drop enum type on downgrade if it exists
    workspacerole_enum.drop(bind, checkfirst=True)